name: novarum_launcher
description: Clean and minimalistic launcher for android.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-151.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  on_click: ^1.1.4
  dynamic_color: ^1.5.4
  battery_plus: ^3.0.2
  material_you_colours: ^0.0.1-pre1
  flutter_layout_grid: ^2.0.1
  flutter_feather_icons: ^2.0.0+1
  fuzzysearch: ^0.1.3
  dart_rss: ^2.0.1
  url_launcher: ^6.1.8
  http: ^0.13.5
  device_apps: ^2.2.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon512x512.png"
  min_sdk_android: 21


fonts:
  - family: WorkSans
    fonts:
      - asset: fonts/Work_Sans/WorkSans-Regular.ttf
      - asset: fonts/Work_Sans/WorkSans-SemiBold.ttf
        weight: 600
      - asset: fonts/Work_Sans/WorkSans-Bold.ttf
        weight: 700
      - asset: fonts/Work_Sans/WorkSans-Italic.ttf
        style: italic
